### PR TITLE
WIP - JS to TS

### PR DESCRIPTION
**Pull request by SneakY-NickY**
WIP PR for conversion of JS files to TS files

### CODE REVIEW

**Comment by SoraSuegami** [comment]
Thank you for your great work!

**Comment by Divide-By-0** [comment]
@SneakY-NickY please send me your paypal/eth address so I can pay you for your contribution! You can email aayushg@mit.edu.

**Comment by SneakY-NickY** [comment]
> @SneakY-NickY please send me your paypal/eth address so I can pay you for your contribution! You can email [aayushg@mit.edu](mailto:aayushg@mit.edu).

I've linked my paypal e-mail in my github profile. Thank you for your kindness! 😄

**Comment by Divide-By-0** [comment]
> > @SneakY-NickY please send me your paypal/eth address so I can pay you for your contribution! You can email [aayushg@mit.edu](mailto:aayushg@mit.edu).
> 
> I've linked my paypal e-mail in my github profile. Thank you for your kindness! 😄

Of course! Do you mind rebasing/merging into #33, since that was done at the same time?

**Comment by SneakY-NickY** [comment]
> > > @SneakY-NickY please send me your paypal/eth address so I can pay you for your contribution! You can email [aayushg@mit.edu](mailto:aayushg@mit.edu).
> > 
> > 
> > I've linked my paypal e-mail in my github profile. Thank you for your kindness! 😄
> 
> Of course! Do you mind rebasing/merging into #33, since that was done at the same time?

I can take a look, although I'm getting quite busy with finals so it'll take a while for me 😓

**Comment by Divide-By-0** [comment]
> > > > @SneakY-NickY please send me your paypal/eth address so I can pay you for your contribution! You can email [aayushg@mit.edu](mailto:aayushg@mit.edu).
> > > 
> > > 
> > > I've linked my paypal e-mail in my github profile. Thank you for your kindness! 😄
> > 
> > 
> > Of course! Do you mind rebasing/merging into #33, since that was done at the same time?
> 
> I can take a look, although I'm getting quite busy with finals so it'll take a while for me 😓

No worries! Isidro and Rigo are on it. Thanks for adding the tests. Let me know when your finals are done!

**Pull request merged**
