### PR TITLE
Rmacedo/update regex to mindfa

### PR DESCRIPTION
**Pull request by bert0RM**

### CODE REVIEW

**Comment by Divide-By-0** [comment]
i dont think u have the latest branch right, the "[add comments for regex and substrings](https://github.com/zkemail/zk-regex/pull/33/commits/e1e9a696a6c5b625f7c78da02aa52b242ee83a18)" one

**Comment by bert0RM** [comment]
> i dont think u have the latest branch right, the "[add comments for regex and substrings](https://github.com/zkemail/zk-regex/pull/33/commits/e1e9a696a6c5b625f7c78da02aa52b242ee83a18)" one

Added

**Comment by Divide-By-0** [comment]
> > i dont think u have the latest branch right, the "[add comments for regex and substrings](https://github.com/zkemail/zk-regex/pull/33/commits/e1e9a696a6c5b625f7c78da02aa52b242ee83a18)" one
> 
> Added

Looks like it reverted?

**Comment by Divide-By-0** [comment]
Can you rebase on main @bert0RM

**Comment by Divide-By-0** [comment]
@Bisht13

**Comment by Divide-By-0** [comment]
I see; since the regexes are now being parsed by Rust, not JS, the simplification to a-z fails.

**Pull request merged**
